### PR TITLE
Game buttons action

### PR DESCRIPTION
**Pull request by deplanty**
# Work in progress
- Add a method `execute` to the button: acts like a "mousebutton up" event was triggered;
- Put button actions in button methods.

# I need your advice
- How to make the button "quit" stop the loop without using `return`?

### CODE REVIEW

**Comment by Hboni** [comment]
First (and you know it) this branch derived from another feature branch, ... not good. 
Second, you have an issue and you ask for discussion, why not create an Issue on github? You can just commit on your branch but ask on an issue instead in a PR.

For your question, we can use another _state variable_ more like "playing", the quit button can change this variable and `self.state` to False, and we can add a condition before delear decision to check if "playing", and quit if not ?

**Comment by deplanty** [comment]
I thought it derived from `bug_fix` automatically (which is a bit stupid)... Now I know!
I used the PR to ask a question cause I don't know if we will be using the Issues or Asana...

I got your point. I'll try something tonight.

**Comment by Hboni** [comment]
Use issues, they exist to aks questions. I suggest you delete your PR, (and maybe your branch) to make something cleaner.

**Comment by deplanty** [comment]
Ok!
I'll do it tonight.

**Pull request closed without merging**
